var external_imgs = {
    "中国": "img/china.jpg",
    "美国": "img/usa.jpg",
    "日本": "img/japan.jpg",
    "加拿大": "img/canada.jpg",
    "英国": "img/uk.jpg",
    "巴西": "img/brazil.jpg",
    "韩国": "img/korea.jpg",
    "德国": "img/german.jpg",
    "法国": "img/france.jpg",
    "Mexico": "img/mexico.jpg",
    "墨西哥": "img/mexico.jpg",
    "意大利": "img/italy.jpg",
    "比利时": "img/belgium.jpg",
    "Singapore": "img/singapore.jpg",
    "新加坡": "img/singapore.jpg",
    "荷兰": "img/netherlands.jpg",
    "俄罗斯": "img/russia.jpg",
    "俄罗斯联邦": "img/russia.jpg",
    "西班牙": "img/spain.jpg",
    "Switzerland": "img/switzerland.jpg",
    "瑞士": "img/switzerland.jpg",
    "爱尔兰": "img/ireland.jpg",
    "印度": "img/india.jpg",
    "印度尼西亚": "img/indonesia.jpg",
    "土耳其": "img/turkey.jpg"
}